name: Build mapless-practice

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get submodules
        run: git submodule update --init --recursive

      - name: Get tar
        run: sudo apt-get install tar

      - name: Get zig
        run: |
          curl https://ziglang.org/download/0.9.1/zig-linux-x86_64-0.9.1.tar.xz -o zig.tar.xz
          tar xf zig.tar.xz

      - name: Build for Linux x86_64
        run: |
          ./zig-linux-x86_64-0.9.1/zig cc -lm -O3 -o finder-x86_64-linux -I cubiomes finder.c \
              cubiomes/biome_tree.c \
              cubiomes/finders.c \
              cubiomes/generator.c \
              cubiomes/layers.c \
              cubiomes/noise.c \
              cubiomes/util.c

      - name: Upload Linux x86_64
        uses: actions/upload-artifact@v3.0.0
        with:
          name: main
          path: finder-x86_64-linux

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            finder-x86_64-linux
